<?xml version="1.0"?>
<robot 
     xmlns:xacro="http://www.ros.org/wiki/xacro" name="pedestal">
     <!-- a simple box onto which Baxter robot can be mounted-->
    <xacro:property name="bodylen" value="0.3" />
    <xacro:property name="bodywidth" value="0.3" />
    <xacro:property name="bodyheight" value="0.85" />

    
    <!--this will be referred to as the "base_link", so code can be
    compatible with baxter on mobot-->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${bodylen} ${bodywidth} ${bodyheight}"/>
            </geometry>
            <origin xyz="0 0 ${bodyheight/2}" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${bodylen} ${bodywidth} ${bodyheight-0.01}"/>
            </geometry>
            <origin xyz="0 0 ${bodyheight/2}" rpy="0 0 0"/>
        </collision>
    </link>
    
  
</robot>
